gptscript-ai/knowledge

- Makefile
- pkg/cmd/main.go
- version/version.go
use `knowledge version` to print the version of the knowledge tool as hardcoded at build time when using the `make build` target
> add: version subcommand

- pkg/config/config.go
- pkg/datastore/datastore.go
- `OPENAI_BASE_URL` should be the full resource host, e.g. https://myresource.openai.azure.com
- new config option `OPENAI_AZURE_DEPLOYMENT` should be the name of the deployed model (overrides `OPENAI_EMBEDDING_MODEL` if set)
> chore: (breaking) cleanup env var and cli flag names

- pkg/cmd/retrieve.go
- pkg/vectorstore/chromem/chromem.go
- pkg/vectorstore/errors.go
- pkg/vectorstore/errors/errors.go
The error `nResults must be > 0` often happens because we reduce the number of requested documents to be <= the number of available documents in a dataset. If the dataset is empty, this is not actually a hard error but something that we can let the LLM session (GPTScript) know without erroring out.
> change: no error on empty collection, so that the LLM session can 'recover' from the tool call

- pkg/cmd/askdir.go
- pkg/cmd/ingest.go
- pkg/datastore/document.go
- pkg/datastore/files.go
- pkg/datastore/ingest.go
- pkg/vectorstore/chromem/chromem.go
- pkg/vectorstore/vectorstores.go
This PR fixes two things:
1. Recursively run askDir/ingest by default. 
2. When ingesting duplicated files with changes, we don't prune the old content. This caused old content being present again in dataset, impacting the query.
> Fix: recursively search files by default, fix file ingestion with edit

- pkg/datastore/textsplitter/markdown_basic/markdown_basic.go
- pkg/datastore/textsplitter/markdown_basic/markdown_basic_test.go
- pkg/datastore/textsplitter/markdown_basic/options.go
This PR adds a pretty basic markdown text splitter, that only considers headings for splitting.
One can choose up to which level of headings to split the text and result chunks which are larger than the defined chunkSize will be chunked further by a secondary splitter (default is a recursiveCharacterSplitter).
Every chunk will be prefixed with the whole markdown heading hierarchy, improving the semantic search results.
Optionally, chunks that consist of headings only (i.e. no content) can be ignored/dropped.
The code follows the functional options pattern like the golc and langchaingo libs for consistency.
> add: basic markdown splitter with limited options

- go.mod
- go.sum
- pkg/client/client.go
- pkg/client/default.go
- pkg/client/flow.go
- pkg/client/standalone.go
- pkg/cmd/client.go
- pkg/cmd/export.go
- pkg/cmd/get_dataset.go
- pkg/cmd/import.go
- pkg/cmd/list_datasets.go
- pkg/cmd/main.go
- pkg/cmd/reset.go
- pkg/cmd/retrieve.go
- pkg/datastore/datastore.go
- pkg/datastore/textsplitter/markdown_basic/markdown_basic.go
- pkg/datastore/textsplitter/markdown_basic/markdown_basic_test.go
- pkg/datastore/types/types.go
- pkg/index/datasets.go
- pkg/vectorstore/chromem/chromem.go
- pkg/vectorstore/vectorstores.go
- `knowledge export <dataset> --output foo.zip`
- `knowledge retrieve -d <dataset> --archive foo.zip "some question"`
- `knowledge list-datasets --archive foo.zip`
- `knowledge get-dataset <dataset> --archive foo.zip`
- `knowledge import foo.zip`
Depends On (currently using fork): https://github.com/philippgille/chromem-go/pull/88
NOTE: there are quite a few rough edges and missing pieces, e.g. the server-mode version of this is not yet implemented.. we'll follow up on this in the future!
> add: commands to export datasets and to import/query them

- examples/subquery_retriever.yaml
- pkg/cmd/client.go
- pkg/cmd/export.go
- pkg/cmd/list_datasets.go
- pkg/cmd/retrieve.go
- pkg/datastore/retrievers/retrievers.go
- pkg/datastore/retrievers/subquery.go
- pkg/flows/config/config.go
- pkg/flows/config/redact.go
- pkg/flows/config/redact_test.go
- pkg/llm/llm.go
Two parts to this PR:
1. Subquery: we ask the LLM to break up the input query into multiple subqueries, if the input is about two different topics or entities, e.g. when comparing two tools. Due to the split, the semantic search is more likely to return distinct results for both topics, which is especially useful when there is no content about the actual comparison.
2. Redact sensitive data: In our debug logs we were printing the configs of flow elements - including LLM API Keys. Those will now be redacted before logging them.
> add: subquery retriever + redact sensitive values in logs

- examples/routing_retriever.yaml
- pkg/client/client.go
- pkg/client/default.go
- pkg/client/standalone.go
- pkg/cmd/edit_dataset.go
- pkg/cmd/main.go
- pkg/datastore/dataset.go
- pkg/datastore/retrieve.go
- pkg/datastore/retrievers/retrievers.go
- pkg/datastore/retrievers/routing.go
- pkg/datastore/retrievers/subquery.go
- pkg/datastore/store/store.go
- pkg/flows/flows.go
- pkg/index/datasets.go
- pkg/index/metadata.go
- pkg/index/models.go
This PR adds
1. CRUD operations for Dataset metadata
2. Routing Retriever, which allows the LLM to select the target dataset based on the provided dataset metadata
> add: dataset metadata + routing retriever

- go.mod
- go.sum
- pkg/datastore/documentloader/defaults.go
- pkg/datastore/documentloader/documentloaders.go
- pkg/datastore/documentloader/documentloaders_test.go
- pkg/datastore/documentloader/mupdf.go
- pkg/datastore/documentloader/pdf/defaults/defaults.go
- pkg/datastore/documentloader/pdf/gopdf/pdf.go
- pkg/datastore/documentloader/pdf/mupdf/pdf.go
- scripts/cross-build.sh
Introduces a go build tag `mupdf` - which requires `CGO_ENABLED=1` to include MuPDF in the build.
Currently, MuPDF is the only piece that requires CGO, so without it, we can build static binaries.
Building **without** `mupdf` is required for linux/arm64 and windows/arm64, because at the moment there are no MuPDF library (C) builds for either.
This PR brings back the pure-Go PDF parser as the default reader for non-mupdf builds.
In the config you can now choose
- `pdf` / `gopdf` -> pure-Go PDF parser
- `mupdf` -> MuPDF (will yield an error on non-mupdf builds)
> add: add back old GoPDF parser and "hide" MuPDF behind mupdf build tag to allow for No-CGO builds for some OS/Arch combos

- tool.gpt
We need to make this tool a context so that when it is added to a
script, the script knows to use it. This also allows us to add
context/workspace as a shared context tool, which is need for this tool
to function properly.
> Fix: Make top-level tool a context

- go.mod
- go.sum
- pkg/client/client.go
- pkg/client/common.go
- pkg/client/default.go
- pkg/client/standalone.go
- pkg/cmd/askdir.go
- pkg/cmd/retrieve.go
- pkg/datastore/retrieve.go
- pkg/datastore/retrievers/keyword.go
- pkg/datastore/retrievers/retrievers.go
- pkg/datastore/retrievers/routing.go
- pkg/datastore/retrievers/subquery.go
- pkg/datastore/store/store.go
- pkg/flows/flows.go
- pkg/server/routes.go
- pkg/vectorstore/chromem/chromem.go
- pkg/vectorstore/vectorstores.go
Upstream: https://github.com/philippgille/chromem-go/pull/96
knowledge retrieve and askdir get new/updated flags:
- `--keyword` / `-w`:
- enable Hybrid search by pre-filtering the dataset for documents containing (or not containing) some given keywords
- use `-` as a prefix for the word to add it to the "not-include" list
- included keywords are OR'd, excluded keywords are AND'd
- Example: `knowledge retrieve -w "foo" -w "bar" -w "-spam" -w "-eggs" "some query"` will retrieve documents that contain either "foo" or "bar" but definitely not "spam" or "eggs"
- Pitfall: `knowledge retrieve "what is foo?" -w "-foo" will likely return nothing (you don't say :O)
- `--dataset` / `-d` can now be used multiple times
- depending on the used retriever (e.g. the default BasicRetriever won't work with …
> add: -w/--keyword flag for retrieve/askdir + allow selecting multiple datasets

- examples/chatgpt-filesearch.yaml
- pkg/client/common.go
- pkg/cmd/askdir.go
- pkg/cmd/client.go
- pkg/cmd/ingest.go
- pkg/datastore/ingest.go
- pkg/datastore/ingest_test.go
- pkg/datastore/textsplitter/textsplitter.go
- pkg/datastore/textsplitter/textsplitter_test.go
- pkg/flows/config/config.go
- pkg/flows/flows.go
```yaml
flows:
chatgpt:
default: true
globals:
ingestion:
textsplitter: # settings which will be merged with the config for any textsplitter implementation
chunkSize: 800
chunkOverlap: 400
ingestion:
- filetypes: ["*"]
textsplitter:
name: text
options:
chunkSize: 811
```
> add: flow-global options

- pkg/client/client.go
- pkg/client/common.go
- pkg/client/standalone.go
- pkg/cmd/askdir.go
- pkg/cmd/ingest.go
- pkg/datastore/documentloader/defaults.go
- pkg/datastore/ingest.go
Regression introduced by #72 
`--err-on-unsupported-file` is **always** `true` when ingesting a single file, but `false` **by default** for directories
> fix: do not error on unsupported file types by default upon ingestion - but add --err-on-unsupported-file flag to toggle that behavior

- examples/hybrid-retriever.yaml
- pkg/datastore/lib/scores/scores.go
- pkg/datastore/retrievers/bm25.go
- pkg/datastore/retrievers/merging.go
- pkg/datastore/retrievers/retrievers.go
- pkg/datastore/retrievers/routing.go
- pkg/datastore/retrievers/subquery.go
- pkg/flows/config/config.go
- pkg/output/redact.go
- pkg/output/redact_test.go
Example flow config:
```yaml
flows:
hybrid:
default: true
retrieval:
retriever:
name: merge
options:
topK: 10
retrievers:
- name: basic
weight: 0.5
options:
topK: 10
- name: bm25
weight: 0.5
options:
topN: 10
k1: 1.2
b: 0.75
cleanStopWords:
- en
- de
```
> add: merging retriever with example for hybrid search using bm25 and semantic search

- examples/no-filenames.yaml
- pkg/datastore/postprocessors/postprocessors.go
- pkg/datastore/transformers/metadata.go
- pkg/datastore/transformers/transformers.go
- pkg/flows/config/config.go
Example:
```
flows:
bm25:
default: true
retrieval:
retriever:
name: basic
options:
topK: 1
postprocessors:
- name: metadata
options:
manipulations:
- operator: add
key: foobar
value: 42
- operator: remove
key: absPath
```
> add: metadata-manipulator transformer & post-processor

- pkg/cmd/ingest.go
- pkg/cmd/retrieve.go
- pkg/datastore/datastore.go
- pkg/datastore/documentloader/defaults.go
- pkg/datastore/lib/scores/scores.go
- pkg/datastore/postprocessors/bm25.go
- pkg/datastore/postprocessors/reduce.go
- pkg/datastore/retrievers/bm25.go
- pkg/datastore/retrievers/merging.go
- pkg/flows/flows.go
- pkg/llm/llm.go
[fix: do not error on unsupported file if single target file is a ZIP](https://github.com/gptscript-ai/knowledge/commit/8955779e985f5e66baaeef88a2f7eac9446dfa31)
[change (retrieve): error on empty query, but just return nothing on '-' as query](https://github.com/gptscript-ai/knowledge/commit/c79c306f0d4993c47cda1b168ce1ad3e8ca087ec)
[change: reduce log spam](https://github.com/gptscript-ai/knowledge/commit/16bd934c198d60f96b124eeb9ad0d67b5e287e7c)
[fix: by default, do not error on unsupported or broken files within an archive](https://github.com/gptscript-ai/knowledge/commit/a9e95df23bc145949b37c171c8f1ed1955b84bb9)
[fix: topK result set reduction was broken (cutoff of last element)](https://github.com/gptscript-ai/knowledge/commit/50c9d7b8b261d6c76fa0bf452f4dbc5c5c3aebe5)
> fix-bundle

- gateway/tool.gpt
- main.go
- pkg/cmd/client.go
- tool.gpt
... extracted the following PRs with changes I made while working on this:
- #101
- #102
> feat: context tool

- pkg/datastore/lib/scores/scores.go
- pkg/datastore/retrievers/bm25.go
- pkg/datastore/retrievers/merging.go
- pkg/datastore/retrievers/retrievers.go
- pkg/datastore/retrievers/routing.go
- pkg/datastore/retrievers/subquery.go
In our default flows, we're using a merging retriever with similarity search and bm25 search.
The similarityScores from the similarity search are already normalized (0-1 range), while the bm25 Scores are not.
Before this change we still did a min/max-normalization even over the observed similarityScores, which distorted them so much that it significantly impacted the merged document score.
For the future we may consider using zScore normalization - #106
> fix: do not min/max-normalize already normalized similarity scores to not distort them

- go.mod
- go.sum
- pkg/datastore/retrievers/bm25.go
Test cases succeeded using the changes implemented upstream: https://github.com/iwilltry42/bm25-go/commit/a928590cc9dac1f92b399595e2d058e713d26078
> fix: bm25 returned NaN scores due to wrong term frequency calculation upstream

- go.mod
- go.sum
https://github.com/iwilltry42/chromem-go/commit/9ae8a6a6d21175d53f9a75a461d00d5e6ea6ef7e
> fix: bump chromem-go fix to include retry-embeddings error handling

- pkg/client/client.go
- pkg/client/default.go
- pkg/client/standalone.go
- pkg/cmd/ingest.go
- pkg/cmd/main.go
- pkg/datastore/ingest.go
- pkg/flows/flows.go
- pkg/log/log.go
- pkg/server/routes.go
- pkg/vectorstore/chromem/chromem.go
Ref #116 
- adds new `--json` root level flag to switch log output to JSON
- we're now using a hierarchical logging approach with logger saved to and loaded from the context, if available
- there's now more logs to represent the progress of a file through the entire pipeline
Here's a breakdown of key used in the logs:
- `flow`: `ingestion` or `retrieval` - currently only implemented for `ingestion`
- `phase`: phase within a flow
`ingestion` flow has these phases: `open` -> `parse` -> `store`
- `stage`: stage within the phase
`open`: `read`
`parse`: `documentloader` -> `textsplitter` -> `transformers`
- global fields are `status` with the following possible values:
- `starting`
- `completed`
- `skipped` -> additional field `reason`
- `failed` -> additional field `error`
- there may be a …
> feat(breaking): add structured json log + make filename mandatory for ingestion

- gateway/tool.gpt
- tool.gpt
Make thread id and script_id optional. At least one of these will be set in otto.
> Fix: make script_id and thread_id optional

- pkg/client/common.go
- pkg/client/default.go
- pkg/client/ignore.go
- pkg/client/metadata.go
- pkg/client/standalone.go
- pkg/datastore/ingest.go
Ref #118 
When ingesting a file or directory (recursively or not), we're now checking if there is a `.knowledge.json` file present in the directory. It's structured like this:
```json
{
"metadata": {
"foo.pdf": {
"baz": "bom",
"foo": "bar"
},
"somedir/bar.pdf": {
"x": "y"
}
}
}
```
This will add the defined k/v pairs as metadata to the documents in the vector store.
`.knowledge.json` files in nested directories will be merged (with override) with parent metadata files.
1. I went with `.knowledge.json` instead of `.metadata.json` because I felt like the latter could be too "common" and we'd run into conflicts. By default, we're including hidden files in the ingestion process, so `.knowledge.json` is not explicitly being ignored.
2. It's JSON with an explicit `metadata` entry so we can add …
> feat: ingestion - include metadata from .knowledge.json on dir level

- pkg/client/common.go
- pkg/datastore/datastore.go
- pkg/datastore/ingest.go
This gives some progress indication for the embeddings generation.
Unfortunately, without modifying the chromem-go code for this, we cannot get the `"progress": "1/3"` style output here, so maybe in Otto we can just do a counter based on the `"status": "starting"` with `"num_documents": 3` being the total number of times it should appear.
```
{"time":"2024-09-19T14:56:15.374927781+02:00","level":"INFO","msg":"Adding documents to collection (generating embeddings)","flow":"ingestion","rootPath":".local/testdata/metadata/Reunion-Under-The-Stars.pdf","filepath":".local/testdata/metadata/Reunion-Under-The-Stars.pdf","phase":"store","num_documents":3,"stage":"vectorstore","vectorstore":"chromem-go","status":"starting"}
{"time":"2024-09-19T14:56:15.374966246+02:00","level":"INFO","msg":"Creating …
```
> feat: add progress indication for embedding generation process

- pkg/datastore/datastore.go
We are printing a ton of embedding logs which makes otto hard to save the output when file is too big.
> Fix: Remove embedding logs to make output concise

- pkg/datastore/datastore.go
Accidentally removed embedding function while it is only supposed to be removing log wrapper...
> Fix: add embedding function back

- pkg/datastore/ingest.go
We need to add proper status to indicate finished state. `Completed` state is not enough because it could be completed state in earlier step while it is still running. 
Also for unsupported files we also emit log so that the file will have a status showing unsupported.
https://github.com/gptscript-ai/otto/issues/86
https://github.com/gptscript-ai/otto/issues/87
> Fix: add proper status to finished state and unsupported files

- go.mod
- go.sum
- pkg/datastore/datastore.go
- pkg/datastore/embeddings/openai/openai.go
- pkg/datastore/embeddings/vertex/vertex.go
This PR updates to use latest embedding model from openai and also apply the timeout fix for embedding api requests which could be block the ingestion
> Fix: update to latest embedding model, apply timeout  and corrupted collection fixes

- tool.gpt
ref https://github.com/gptscript-ai/otto/issues/130
> fix: make tool.gpt and gateway/tool.gpt match

- pkg/datastore/documentloader/pdf/mupdf/pdf.go
ref #135 
Recovering from the CGO panic is unfortunately not possible. But the locking doesn't introduce any significant latency, so we're good to go.
> fix: use a lock for extracting text from pdf via mupdf to avoid cgo panic (issue #135)

- pkg/client/client.go
- pkg/client/default.go
- pkg/client/standalone.go
- pkg/cmd/delete_file.go
- pkg/cmd/get_file.go
- pkg/cmd/main.go
- pkg/datastore/files.go
Adds commands
- `knowledge get-file -d <dataset> <file-id | file-abs-path | file-rel-path>`
- `knowledge delete-file -d <dataset> <file-id | file-abs-path | file-rel-path>`
`file-rel-path` will only work for files existing under that relative path in the filesystem.
The other two work as direct identifiers.
> add: knowledge delete-file & knowledge get-file

- pkg/client/common.go
- pkg/client/ignore.go
If there is a `.knowignore` file in the root path of the ingested directory, it will be used.
Also, this PR now sorts the ignore patterns in increasing priority as expected by the gitignore library:
1. Default ignore file
2. User-provided ignore file
3. User-provided ignore extensions
4. Default ignore patterns
> add: use .knowignore in top-level ingestion path if exists

- delete-file.gpt
- ingest.gpt
- pkg/client/common.go
This PR adds delete-file.gpt so that it can delete file on demand, and also disable prune when ingesting. It also fixed a bug where ignore file doesn't work
> Add delete file options, don't run prune

- examples/structured-ingestion/example.json
- go.mod
- pkg/client/ignore.go
- pkg/cmd/load.go
- pkg/datastore/documentloader/documentloaders.go
- pkg/datastore/documentloader/structured/structured.go
- pkg/vectorstore/sqlite-vec/sqlite-vec.go
Example format:
```json
{
"metadata": {
"source": "https://example.com",
"filename": "foo.pdf"
},
"documents": [
{
"metadata": {
"page": 1
},
"content": "This is the first page of the document."
},
{
"metadata": {
"page": 2
},
"content": "This is the second page of the document."
}
]
}
```
`knowledge load` supports this as a default now: `knowledge load mydoc.pdf -` will print the loaded content from mydoc.pdf in the above format.
You may as well verify your own structured output via `diff <(cat examples/structured-ingestion/example.json) <(knowledge load examples/structured-ingestion/example.json --loader "structured" -)` (there may be formatting differences).
Note: `knowledge load` sets the global `source` metadata to the source file that you give it.
> add: structured json dataloader
